

services:
  container:
    build: .
    image: archilitav/container:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    command: ["npm", "start"]
    
    