name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Error: DOCKER_PASSWORD secret is not set."
            exit 1
          fi
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Compose
        run: |
          docker-compose build
          docker tag marketing_marketing:latest ${{ secrets.DOCKER_USERNAME }}/marketing:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/marketing:latest
